github action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,79 +1,127 @@
-name: 'build-apps'
-
+name: Release
 on: workflow_dispatch
 
+env:
+  BIN_NAME: hes-game
+  PROJECT_NAME: half-earth-socialism
+
 jobs:
-  build-binaries:
-    permissions:
-      contents: write
+  dist:
+    name: Dist
+    runs-on: ${{ matrix.os }}
     strategy:
-      fail-fast: false
+      fail-fast: false # don't fail other jobs if one fails
       matrix:
+        build: [x86_64-linux, x86_64-macos, x86_64-windows]
         include:
-          - platform: 'macos-latest'
-            args: '--mac'
-          - platform: 'ubuntu-22.04'
-            args: '--linux'
-          - platform: 'windows-latest'
-            args: '--win'
+        - build: x86_64-linux
+          os: ubuntu-latest
+          rust: stable
+          target: x86_64-unknown-linux-gnu
+        - build: x86_64-macos
+          os: macos-latest
+          rust: stable
+          target: x86_64-apple-darwin
+        - build: x86_64-windows
+          os: windows-latest
+          rust: stable
+          target: x86_64-pc-windows-msvc
 
-    runs-on: ${{ matrix.platform }}
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout sources
+        uses: actions/checkout@v2
         with:
-          submodules: 'true'
+          submodules: true
 
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: lts/*
-
-      - name: Setup Rust
+      - name: Install ${{ matrix.rust }} toolchain
         uses: actions-rs/toolchain@v1
         with:
-          default: true
-          override: true
           profile: minimal
-          toolchain: nightly
-          target: ${{ matrix.platform == 'macos-latest' && 'x86_64-apple-darwin' || '' }}
+          toolchain: ${{ matrix.rust }}
+          target: ${{ matrix.target }}
+          override: true
 
-      - name: Setup Rust cache
-        uses: Swatinem/rust-cache@v2
+      - name: Build release binary
+        uses: actions-rs/cargo@v1
         with:
-          workspaces: hes-game
+          command: build
+          args: --release --locked --target ${{ matrix.target }}
 
-      - uses: jetli/trunk-action@v0.5.0
+      - name: Strip release binary (linux and macos)
+        if: matrix.build == 'x86_64-linux' || matrix.build == 'x86_64-macos'
+        run: strip "target/${{ matrix.target }}/release/$BIN_NAME"
+
+      - name: Build archive
+        shell: bash
+        run: |
+          mkdir dist
+          if [ "${{ matrix.os }}" = "windows-latest" ]; then
+            cp "target/${{ matrix.target }}/release/$BIN_NAME.exe" "dist/"
+          else
+            cp "target/${{ matrix.target }}/release/$BIN_NAME" "dist/"
+          fi
+
+      - uses: actions/upload-artifact@v2.2.4
         with:
-          # Optional version of trunk to install(eg. 'v0.19.1', 'latest')
-          version: 'v0.20.3'
+          name: bins-${{ matrix.build }}
+          path: dist
 
-      - name: Install wasm target
-        run: rustup target add wasm32-unknown-unknown
+  publish:
+    name: Publish
+    needs: [dist]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout sources
+        uses: actions/checkout@v2
+        with:
+          submodules: false
 
-      - name: Setup electron
-        working-directory: electron
+      - uses: actions/download-artifact@v2
+      - run: ls -al bins-*
+
+      - name: Calculate tag name
         run: |
-          cp package.game.json package.json
-          yarn install --dev
+          name=dev
+          if [[ $GITHUB_REF == refs/tags/v* ]]; then
+            name=${GITHUB_REF:10}
+          fi
+          echo ::set-output name=val::$name
+          echo TAG=$name >> $GITHUB_ENV
+        id: tagname
 
-      - name: Build game
-        env:
-          PLATFORM: STEAM
-        run: trunk build --release --config hes-game/Trunk.toml --dist electron/site
-
-      - name: Build and release game app
-        working-directory: electron
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: yarn build ${{ matrix.args }} --publish always
-
-      - name: Build editor
-        run: trunk build --release --config hes-editor/Trunk.toml --dist electron/site
-
-      - name: Build and release editor app
-        working-directory: electron
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Build archive
+        shell: bash
         run: |
-          cp package.editor.json package.json
-          yarn build ${{ matrix.args }} --publish always
+          set -ex
+
+          rm -rf tmp
+          mkdir tmp
+          mkdir dist
+
+          for dir in bins-* ; do
+              platform=${dir#"bins-"}
+              unset exe
+              if [[ $platform =~ "windows" ]]; then
+                  exe=".exe"
+              fi
+              pkgname=$PROJECT_NAME-$TAG-$platform
+              mkdir tmp/$pkgname
+              # cp LICENSE README.md tmp/$pkgname
+              mv bins-$platform/$BIN_NAME$exe tmp/$pkgname
+              chmod +x tmp/$pkgname/$BIN_NAME$exe
+
+              if [ "$exe" = "" ]; then
+                  tar cJf dist/$pkgname.tar.xz -C tmp $pkgname
+              else
+                  (cd tmp && 7z a -r ../dist/$pkgname.zip $pkgname)
+              fi
+          done
+
+      - name: Upload binaries to release
+        uses: svenstaro/upload-release-action@v2
+        with:
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
+          file: dist/*
+          file_glob: true
+          tag: ${{ steps.tagname.outputs.val }}
+          overwrite: true
